--TABLES--
/*
    CUSTOMERS
    ->customer_id
    ->first_name
    ->last_name
    ->city
    ->state
    ->signup_date

    PRODUCTS
    ->product_id
    ->product_name
    ->category
    ->price

    ORDERS
    ->order_id
    ->customer_id
    ->order_date

    ORDER_ITEMS
    ->order_item_id
    ->order_id
    ->product_id
    ->quantity

*/

--Show the total number of customers in the database
SELECT COUNT(*)
FROM customers;

--Show how many customers live in chicago
SELECT COUNT(*)
FROM customers
WHERE city = 'Chicago';

--Show how many different cities are in the customers list
SELECT COUNT(DISTINCT city)
FROM customers;

--Show each city along with how many people live there
SELECT city, COUNT(*)
from customers
GROUP BY city;

--Find earliest customer signup date in entire database
SELECT MIN(signup_date)
from customers;

--For each city, show the earliest signupdate from that city
SELECT city, MIN(signup_date)
from customers
GROUP BY city;

--Find the total dollar value of all products (assume one of each product)
SELECT SUM(price)
FROM products;

--For each product category, show the average price
SELECT AVG(price) AS "Average category price of items", category
FROM products
GROUP BY category;

--Show all products priced between 20 and 100
SELECT *
FROM products
WHERE price BETWEEN 20 AND 100
ORDER BY price;

--Show all customers who live in chicago, elgin or peoria
SELECT *
FROM customers
WHERE city IN('Chicago','Elgin','Peoria')
ORDER BY city;

--Show each customers first name, last name and the date of each order they placed
SELECT customers.first_name, customers.last_name, orders.order_date
FROM customers
JOIN orders ON customers.customer_id = orders.customer_id
ORDER BY customers.customer_id;

--Show every ordered product with customers first name, last name, produc name, and quantity ordered
SELECT customers.first_name, customers.last_name, products.product_name, order_items.quantity
FROM customers
JOIN orders
ON customers.customer_id = orders.customer_id
JOIN order_items
ON orders.order_id = order_items.order_id
JOIN products 
ON order_items.product_id = products.product_id;

--Show each ordered product with its product name, quantity, price and total cost
SELECT products.product_name, order_items.quantity, products.price, products.price * order_items.quantity AS "Total Cost"
FROM products
JOIN order_items
ON products.product_id = order_items.product_id;

--Show total revenue for each product category
SELECT products.category, SUM(products.price * order_items.quantity) AS "Total revenue from category"
FROM products
JOIN order_items
ON products.product_id = order_items.product_id
GROUP BY products.category;

--Show total revenue generated by each customer
SELECT CONCAT(customers.first_name,' ', customers.last_name), SUM(products.price * order_items.quantity)
FROM customers
JOIN orders
ON customers.customer_id = orders.customer_id
JOIN order_items 
ON orders.order_id = order_items.order_id
JOIN products 
ON products.product_id = order_items.product_id
GROUP BY CONCAT(customers.first_name,' ', customers.last_name);